### ISSUE TITLE
update PyPi docs

### ISSUE THREAD

**Issue by greedo** [croach/Flask-Fixtures#13]
[PyPi docs](https://pypi.python.org/pypi/Flask-Fixtures/0.3.1) example show use of the `FixturesMixin` module which is does not exist in the 0.3.1 release.

![example](https://cloud.githubusercontent.com/assets/410872/7339422/e7765db8-ec3b-11e4-947f-123105e06dc4.png)

Should be an easy fix. I use this package everyday. Thanks for your work on it!

**Comment by croach** [comment]
Rather than updating the docs to match the code, I updated the code :smile:
